# Generated by Django 4.0.4 on 2024-08-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=50)),
                ('nme', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('post_image', models.FileField(upload_to='pictures')),
            ],
            options={
                'db_table': 'postadd',
            },
        ),
        migrations.CreateModel(
            name='PredictionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=222)),
                ('prediction', models.CharField(max_length=34)),
                ('probability', models.CharField(max_length=34)),
                ('time_of_visit', models.DateTimeField()),
            ],
            options={
                'db_table': 'prediction_details',
            },
        ),
        migrations.CreateModel(
            name='smodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('p_image', models.FileField(upload_to='profile')),
            ],
            options={
                'db_table': 'p_image',
            },
        ),
    ]
